// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exhdpwpumugbwzalbwzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4aGRwd3B1bXVnYnd6YWxid3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDkxODMsImV4cCI6MjA2MzA4NTE4M30.pMs85TRwMwuom4bVML98wQ-g1IwMW8FhkiJfV93CVW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);